/**
 * Kaushal Engineering Talent Infrastructure
 * Shared Constants (CJS compatible)
 */

const ROLES = {
  CANDIDATE: 'CANDIDATE',
  REVIEWER: 'REVIEWER',
  RECRUITER: 'RECRUITER',
  ADMIN: 'ADMIN',
};

const CAPABILITY_DIMENSIONS = {
  BACKEND_APIS: 'BACKEND_APIS',
  DATABASE_ENGINEERING: 'DATABASE_ENGINEERING',
  SYSTEM_DESIGN: 'SYSTEM_DESIGN',
  TESTING_RELIABILITY: 'TESTING_RELIABILITY',
  PERFORMANCE_OPTIMIZATION: 'PERFORMANCE_OPTIMIZATION',
  SECURITY_DEFENSE: 'SECURITY_DEFENSE',
  DEVOPS_INFRASTRUCTURE: 'DEVOPS_INFRASTRUCTURE',
};

const SUBMISSION_STATUSES = {
  IN_PROGRESS: 'IN_PROGRESS',
  SUBMITTED: 'SUBMITTED',
  TESTING: 'TESTING',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED',
};

const EVIDENCE_TYPES = {
  REPOSITORY: 'REPOSITORY',
  TEST_RUN: 'TEST_RUN',
  BENCHMARK_TELEMETRY: 'BENCHMARK_TELEMETRY',
  ADR: 'ADR',
  PEER_REVIEW: 'PEER_REVIEW',
  DEFENSE_ROUND: 'DEFENSE_ROUND',
  CHAOS_REPORT: 'CHAOS_REPORT',
};

const BRAND = {
  NAME: 'Kaushal',
  TAGLINE: "Don't claim your skills. Prove them.",
  WORKFLOW: 'BUILD → DOCUMENT → REVIEW → VERIFY → RANK → DISCOVER → HIRE',
  VERSION: '2.5',
};

module.exports = {
  ROLES,
  CAPABILITY_DIMENSIONS,
  SUBMISSION_STATUSES,
  EVIDENCE_TYPES,
  BRAND,
};
